version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: turp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: turp_saas
      MYSQL_USER: turp_user
      MYSQL_PASSWORD: turp_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./api/init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./api/iwrs_schema.sql:/docker-entrypoint-initdb.d/01_iwrs_schema.sql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: turp_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"

volumes:
  db_data:
